[server.log]
level = "info" # crit, error, warning, info, debug
# file = "/var/log/diadem.log"

[server.golbat]
url = "http://127.0.0.1:9001"
secret = ""

# This can be configured in Fletchling. Match the string to its config
defaultNestName = "Unknown Nest"

# Dragonite integration for scout
[server.dragonite]
url = "http://127.0.0.1:7272"
secret = ""

# Optional Koji integrtion. Uncomment to disable
[server.koji]
url = "http://127.0.0.1:8080"
secret = "secret"
projectName = "reactmap"

# For address search, both Pelias and Nominatim are supported.
# Using Pelias over Nominatim is highly recommended. Refer to the readme for more info.
#
#[server.pelias]
#url = "https://api.geocode.earth/"
#apiKey = "key"

#[server.nominatim]
#url = "http://127.0.0.1:500"
#basicAuth = ""

[server.auth]
enabled = true
optional = true

[server.auth.discord]
clientId = ""
clientSecret = ""
redirectUri = "https://map.co/login/discord/callback"

[client.discord]
serverLink = "https://discord.com/invite/VGgsQN2hYG"
serverId = "1359028304128245934"

# Permissions work by defining permission sets.
# When a user fulfills every requirement in that set,
# they will allow access to every configured feature,
# only in the configured areas.
#
# User requirements:
#   - everyone: bool
#   - loggedIn: bool
#   - guildId:  id
#   - roleId:   id
#
# Allows access to:
#   - areas:    name[]    (area name, as configured in koji)
#   - features: feature[] (*, pokemon, gym, pokestop, station, weather, s2cell, scout)
#
# Below are some examples

# Every user gets access to gyms and pokestops in New York
[[server.permissions]]
everyone = true
areas = ["New York"]
features = ["gym", "pokestop"]

# Every logged-in user gets access to all Power Spots
# Above permissions are also granted, since these users also fulfill those requirements
[[server.permissions]]
loggedIn = true
features = ["station"]

# Every user who's a member of my Malte# server gets access to all Pokemon and Scout
# Above permissions are also granted, since these users also fulfill those requirements
[[server.permissions]]
guildId = "1359028304128245934"
features = ["pokemon", "scout"]

# Every user with that specific role gets access to every feature in Tokyo
# Above permissions are also granted, since these users also fulfill those requirements
[[server.permissions]]
guildId = "1359028304128245934"
roleId = "1483326963558653982"
areas = ["Tokyo"]
features = ["*"]

[server.db]
host = "127.0.0.1"
port = 3306
database = "golbat"
user = ""
password = ""

[server.internalDb]
host = "127.0.0.1"
port = 3306
database = "diadem"
user = ""
password = ""

[client.general]
mapName = "Diadem"
defaultLocale = "en"  # Only used in link previews, client locale is set based on user preference
customHome = false  # If enabled, path / will show the config/Home.svelte component, so you can build your own homepage. The map can be found under /map

# Starting map position for new users
defaultLat = 51.516855
defaultLon = -0.080500
defaultZoom = 15

### Map Styles

[[client.mapStyles]]
id = "positron"
name = "Positron"
url = "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json"
default = "light"

[[client.mapStyles]]
id = "dark"
name = "Dark"
url = "https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
default = "dark"

[[client.mapStyles]]
id = "voyager"
name = "Voyager"
url = "https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json"


### UICON Sets


[[client.uiconSets]]
id = "DEFAULT"  # One DEFAULT is required, and it's intended to be this
name = "GO"
url = "https://raw.githubusercontent.com/WatWowMap/wwm-uicons/main/"

base = { scale = 0.5 }
gym = { offsetY = -41 }
raid_pokemon = { scale = 1.2, offsetY = -50 }
raid_pokemon_6 = { scale = 1.2, offsetY = -120 }
raid_egg = { scale = 0.17, offsetY = -120 }
raid_egg_6 = { scale = 0.17, offsetY = -230 }

[[client.uiconSets]]
id = "pogoOutline"
name = "GO"
url = "https://raw.githubusercontent.com/whitewillem/PogoAssets/refs/heads/main/uicons-outline/"

base = { scale = 0.5 }
pokemon = { default = true, scale = 0.4 }
gym = { default = true, offsetY = -26, offsetX = -14 }
raid_pokemon = { scale = 0.8, offsetX = -11, offsetY = -30 }
raid_egg = { scale = 0.24, offsetX = -25, offsetY = -40 }

[[client.uiconSets]]
id = "home"
name = "Home"
url = "https://raw.githubusercontent.com/nileplumb/PkmnHomeIcons/master/UICONS_OS_128/"

base = { scale = 0.25 }
pokemon = true
pokestop = true

[[client.uiconSets]]
id = "shuffle"
name = "Shuffle"
url = "https://raw.githubusercontent.com/nileplumb/PkmnShuffleMap/master/UICONS/"

base = { scale = 0.09 }
pokemon = { scale = 0.5 }
pokestop = { default = true, offsetY = -25, scale = 0.5 }
station = { default = true, offsetY = -25, scale = 0.5 }
quest = { scale = 0.4, offsetX = -40, offsetY = -40, spacing = 60 }
invasion = { scale = 0.35, offsetX = 40, offsetY = -44, spacing = 60 }
max_battle = { scale = 0.4, offsetY = -50 }

[[client.uiconSets]]
id = "shuffleShiny"
name = "Shiny"
url = "https://raw.githubusercontent.com/jms412/PkmnShuffleMap/master/UICONS_Half_Shiny_128/"

base = { scale = 0.25 }
pokemon = true

